name: Compress Projects and Release

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Compress directories
        run: |
          for dir in */; do
            base=$(basename "$dir")
            zip -r "${base}.zip" "$dir"
            echo "${base}.zip" >> zipfiles.txt
          done

      - name: Create Release and Upload Assets
        run: |
          files=$(cat zipfiles.txt)
          echo "files: $files"
          echo "FILES=$files" >> $GITHUB_ENV
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}