name: Compress Projects and Release

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Compress directories
        run: |
          for dir in */; do
            base=$(basename "$dir")
            zip -r "${base}.zip" "$dir"
            echo "${base}.zip" >> zipfiles.txt
          done

      # - name: Get latest tag
      #   id: gettag
      #   run: |
      #     TAG=$(git describe --tags --abbrev=0 2>/dev/null)
      #     if [ "$?" -ne 0 ]; then
      #       echo "No tags found"
      #       echo ::set-output name=tag::
      #     else
      #       echo ::set-output name=tag::$TAG
      #     fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        run: |
          while IFS= read -r asset_path
          do
            asset_name=$(basename $asset_path)
            echo "Uploading $asset_path as $asset_name"
            curl \
              --data-binary @"$asset_path" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type $asset_path)" \
              "${{ steps.create_release.outputs.upload_url }}=$asset_name"
          done < zipfiles.txt